steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'logOpenWeather', '--trigger-http', '--runtime', 'nodejs6', '--entry-point', 'logOpenWeather']
  dir: 'functions'

