steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'logOpenWeather', 'GET', '--runtime', 'Node.js 6', '--entry-point', 'logOpenWeather']
  dir: 'functions'
